"""initial_migration

Revision ID: 5243d4412178
Revises: None
Create Date: 2026-09-28 18:01:03.499784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5243d4412178'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('document_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_margin', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('target_margin', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenant_sku', 'products', ['tenant_id', 'sku'], unique=True)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_table('competitor_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('competitor_name', sa.String(length=100), nullable=False),
    sa.Column('captured_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('suggested_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('calculated_margin', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('outliers_purged_count', sa.Integer(), nullable=False),
    sa.Column('is_feasible', sa.Boolean(), nullable=False),
    sa.Column('reason_unfeasible', sa.String(length=255), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing_history')
    op.drop_table('competitor_prices')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index('idx_tenant_sku', table_name='products')
    op.drop_table('products')
    op.drop_table('tenants')
    # ### end Alembic commands ###